# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [202]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [203]:
print("Numpy version:", np.__version__)

print(np.show_config())

Numpy version: 2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [204]:
a = np.random.random((2,3,5)) # floats [0.-1.)

# a = np.random.randint(0,10,size=(2,3,5)) # ints [0-9]

# a = np.random.random_sample((2,3,5)) # random floats in the half-open interval [0.0, 1.0) (so really in this case same as .random())



### 4. Print a.


In [205]:
print(a)


[[[0.12738955 0.92457946 0.78368204 0.81504765 0.16759557]
  [0.7258843  0.74213491 0.08296627 0.73803456 0.09067896]
  [0.27939732 0.60439623 0.57105178 0.90979441 0.89481964]]

 [[0.68238749 0.273154   0.20994017 0.28290439 0.18978885]
  [0.48037444 0.81744683 0.48025435 0.61458417 0.00123227]
  [0.4663098  0.24219147 0.69562503 0.83918424 0.27820256]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [206]:
b = np.ones((5,2,3))



### 6. Print b.


In [207]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [208]:
# a and b have the same number of elements despite the different shapes, so their sizes are equal:
print("a and b have equal sizes:", a.size == b.size)

a and b have equal sizes: True



### 8. Are you able to add a and b? Why or why not?


In [209]:
# a and b cannot be added together because the shapes of the 3d arrays are different
# a + b



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
# i would personally prefer to reshape it, it's more intuitive for the task than transpose
c = np.reshape(b, (2,3,5))

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [211]:
# using transpose

alt_c = np.transpose(a, (0,1,2))
alt_c

array([[[0.12738955, 0.92457946, 0.78368204, 0.81504765, 0.16759557],
        [0.7258843 , 0.74213491, 0.08296627, 0.73803456, 0.09067896],
        [0.27939732, 0.60439623, 0.57105178, 0.90979441, 0.89481964]],

       [[0.68238749, 0.273154  , 0.20994017, 0.28290439, 0.18978885],
        [0.48037444, 0.81744683, 0.48025435, 0.61458417, 0.00123227],
        [0.4663098 , 0.24219147, 0.69562503, 0.83918424, 0.27820256]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [212]:
d = a + c

d

# addition is possible since the 
# each element in a is added to the element in the equivalent position in c

array([[[1.12738955, 1.92457946, 1.78368204, 1.81504765, 1.16759557],
        [1.7258843 , 1.74213491, 1.08296627, 1.73803456, 1.09067896],
        [1.27939732, 1.60439623, 1.57105178, 1.90979441, 1.89481964]],

       [[1.68238749, 1.273154  , 1.20994017, 1.28290439, 1.18978885],
        [1.48037444, 1.81744683, 1.48025435, 1.61458417, 1.00123227],
        [1.4663098 , 1.24219147, 1.69562503, 1.83918424, 1.27820256]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [213]:
print(a)
print("\n", d)

# each element in d at the equivalent position compared to a is exactly 1 larger than in a
# this is because d was made from the addition of the array a with an array of ones


[[[0.12738955 0.92457946 0.78368204 0.81504765 0.16759557]
  [0.7258843  0.74213491 0.08296627 0.73803456 0.09067896]
  [0.27939732 0.60439623 0.57105178 0.90979441 0.89481964]]

 [[0.68238749 0.273154   0.20994017 0.28290439 0.18978885]
  [0.48037444 0.81744683 0.48025435 0.61458417 0.00123227]
  [0.4663098  0.24219147 0.69562503 0.83918424 0.27820256]]]

 [[[1.12738955 1.92457946 1.78368204 1.81504765 1.16759557]
  [1.7258843  1.74213491 1.08296627 1.73803456 1.09067896]
  [1.27939732 1.60439623 1.57105178 1.90979441 1.89481964]]

 [[1.68238749 1.273154   1.20994017 1.28290439 1.18978885]
  [1.48037444 1.81744683 1.48025435 1.61458417 1.00123227]
  [1.4663098  1.24219147 1.69562503 1.83918424 1.27820256]]]



### 12. Multiply a and c. Assign the result to e.


In [214]:
e = a * c

e

array([[[0.12738955, 0.92457946, 0.78368204, 0.81504765, 0.16759557],
        [0.7258843 , 0.74213491, 0.08296627, 0.73803456, 0.09067896],
        [0.27939732, 0.60439623, 0.57105178, 0.90979441, 0.89481964]],

       [[0.68238749, 0.273154  , 0.20994017, 0.28290439, 0.18978885],
        [0.48037444, 0.81744683, 0.48025435, 0.61458417, 0.00123227],
        [0.4663098 , 0.24219147, 0.69562503, 0.83918424, 0.27820256]]])



### 13. Does e equal to a? Why or why not?


In [215]:
a == e

# since c is an array full of ones, each value in a was multiplied by one, meaning they stay the same
# therefore a and e end up equal

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [216]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)


1.9245794584702098 1.0012322675028114 1.5003677566661073


In [217]:
np.shape(d)

(2, 3, 5)

In [218]:
d.shape

(2, 3, 5)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [219]:
f = np.empty(shape=(d.shape))
display(f)

# expectation: array is of same shape as d but populated with 0
# reality: the shape is the same but the values are populated based on values that exist in memory already

array([[[0.12738955, 0.92457946, 0.78368204, 0.81504765, 0.16759557],
        [0.7258843 , 0.74213491, 0.08296627, 0.73803456, 0.09067896],
        [0.27939732, 0.60439623, 0.57105178, 0.90979441, 0.89481964]],

       [[0.68238749, 0.273154  , 0.20994017, 0.28290439, 0.18978885],
        [0.48037444, 0.81744683, 0.48025435, 0.61458417, 0.00123227],
        [0.4663098 , 0.24219147, 0.69562503, 0.83918424, 0.27820256]]])

In [220]:
# so let's create a clean array to work with
f = np.zeros(shape=(d.shape))
display(f)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [221]:
# based on each value falling into one of the following categories,
# fill the values in array f
f[d == d_mean] = 50
f[d == d_max] = 100
f[d == d_min] = 0
f[(d < d_max) & (d > d_mean)] = 75
f[(d < d_mean) & (d > d_min)] = 25







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [222]:
display(d)

display(f)

# the mean value is not represented in the array as an element, but was purely calculated, thus there is no value 50
# one occurence of both 0 and 100 to represent the minimum and maximum values in the array
# all other values fall in between the extremes and the mean and are represented by 25s and 75s filling most of the array
# which is what was expected

# based on an array populated by simpler values, potentially the mean would also be represented in arrat f, but with floats of significant precision it's unlikely

array([[[1.12738955, 1.92457946, 1.78368204, 1.81504765, 1.16759557],
        [1.7258843 , 1.74213491, 1.08296627, 1.73803456, 1.09067896],
        [1.27939732, 1.60439623, 1.57105178, 1.90979441, 1.89481964]],

       [[1.68238749, 1.273154  , 1.20994017, 1.28290439, 1.18978885],
        [1.48037444, 1.81744683, 1.48025435, 1.61458417, 1.00123227],
        [1.4663098 , 1.24219147, 1.69562503, 1.83918424, 1.27820256]]])

array([[[ 25., 100.,  75.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  75.]],

       [[ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  75.,  25.,  75.,   0.],
        [ 25.,  25.,  75.,  75.,  25.]]])

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [223]:
# creating the array to which put the letter values
# create a new array but initialise it for strings since that is what the inputs will be
g = np.full(d.shape, "", dtype=str)
g

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [224]:
# again fill the array g based on which category each of the values in d fall into
g[d == d_mean] = "C"
g[d == d_max] = "A"
g[d == d_min] = "E"
g[(d < d_max) & (d > d_mean)] = "B"
g[(d < d_mean) & (d > d_min)] = "D"

In [225]:
g

array([[['D', 'A', 'B', 'B', 'D'],
        ['B', 'B', 'D', 'B', 'D'],
        ['D', 'B', 'B', 'B', 'B']],

       [['B', 'D', 'D', 'D', 'D'],
        ['D', 'B', 'D', 'B', 'E'],
        ['D', 'D', 'B', 'B', 'D']]], dtype='<U1')